table DANE_Polska
	lineageTag: 73ba2c14-52bb-47f1-a5f0-a0c2e21c6620

	column Kod
		dataType: int64
		formatString: 0
		lineageTag: 704b0d3d-c505-498a-b977-78c1874a9b39
		summarizeBy: sum
		sourceColumn: Kod

		annotation SummarizationSetBy = Automatic

	column Nazwa
		dataType: string
		lineageTag: 0b9029d9-0e81-443b-b711-2bffc53c3a98
		summarizeBy: none
		sourceColumn: Nazwa

		annotation SummarizationSetBy = Automatic

	column 'Turyści zagraniczni/Noclegi'
		dataType: string
		lineageTag: cb49f85e-808b-4e76-bf8d-76f1aa6cbfa5
		summarizeBy: none
		sourceColumn: Turyści zagraniczni/Noclegi

		annotation SummarizationSetBy = Automatic

	column Kraje
		dataType: string
		lineageTag: e3877316-805a-4ef5-9829-0ec6f7d0fb21
		summarizeBy: none
		sourceColumn: Kraje

		annotation SummarizationSetBy = Automatic

	column Rok
		dataType: int64
		formatString: 0
		lineageTag: e5b13e3a-9fbd-44fb-9328-7b27ed5fa231
		summarizeBy: none
		sourceColumn: Rok

		annotation SummarizationSetBy = Automatic

	column Wartosc
		dataType: int64
		formatString: 0
		lineageTag: 4c9aba7e-8bd2-48b1-a032-3c7a7eca62c3
		summarizeBy: sum
		sourceColumn: Wartosc

		annotation SummarizationSetBy = Automatic

	column 'Turyści/Noclegi - etykieta'
		dataType: string
		lineageTag: 798cf209-2d8b-4938-aeeb-8518c8099409
		summarizeBy: none
		sourceColumn: Turyści/Noclegi - etykieta

		annotation SummarizationSetBy = Automatic

	partition DANE_Polska = m
		mode: import
		source =
				let
				    Źródło = Excel.Workbook(File.Contents("D:\AnalizaDanych\000_projekty\KJD_Turysci\KJD_Turysci\data\1_TurysciZagraniczniWgKrajow_2016-2025_WojewodztwaPowiaty_DLUGIE.xlsx"), null, true),
				    DANE_Sheet = Źródło{[Item="DANE",Kind="Sheet"]}[Data],
				    #"Nagłówki o podwyższonym poziomie" = Table.PromoteHeaders(DANE_Sheet, [PromoteAllScalars=true]),
				    #"Zmieniono typ" = Table.TransformColumnTypes(#"Nagłówki o podwyższonym poziomie",{{"Kod", Int64.Type}, {"Nazwa", type text}, {"Turyści zagraniczni/Noclegi", type text}, {"Kraje", type text}, {"Rok", Int64.Type}, {"Wartosc", Int64.Type}, {"Jednostka miary", type text}, {"Atrybut", type text}}),
				    #"Usunięto kolumny" = Table.RemoveColumns(#"Zmieniono typ",{"Jednostka miary", "Atrybut"}),
				    #"Przefiltrowano wiersze" = Table.SelectRows(#"Usunięto kolumny", each ([Nazwa] = "POLSKA")),
				    #"Dodano kolumnę warunkową" = Table.AddColumn(#"Przefiltrowano wiersze", "Turyści/Noclegi - etykieta", each if Text.Contains([#"Turyści zagraniczni/Noclegi"], "turyści zagraniczni") then "Turyści" else if Text.Contains([#"Turyści zagraniczni/Noclegi"], "udzielone noclegi") then "Noclegi" else null)
				in
				    #"Dodano kolumnę warunkową"

	annotation PBI_NavigationStepName = Nawigacja

	annotation PBI_ResultType = Table

